/*
 * main.cpp — STM32F407 ExecuTorch inference runner
 *
 * Loads a .pte model from flash (as a C array generated by xxd -i),
 * runs inference, and stores results in volatile variables for
 * inspection with a debugger.
 *
 * To verify results: attach GDB and inspect 'correct' and 'results'
 * at the final while(1).
 */

#include <cstdint>
#include <cstring>

#include "executorch/runtime/executor/program.h"
#include "executorch/runtime/executor/method.h"
#include "executorch/runtime/core/exec_aten/exec_aten.h"
#include "executorch/runtime/core/portable_type/tensor_impl.h"
#include "executorch/runtime/core/hierarchical_allocator.h"
#include "executorch/runtime/platform/runtime.h"
#include "executorch/extension/data_loader/buffer_data_loader.h"

/*
 * Generated by CMakeLists.txt using:
 *   xxd -i tiny_model.pte > tiny_model_pte.h
 * run from the models/ directory so variable names are clean.
 *
 * The array has __attribute__((aligned(16))) added by CMake post-processing
 * to satisfy the FlatBuffer parser's alignment requirement.
 */
#include "tiny_model_pte.h"

using namespace executorch::runtime;
using namespace executorch::extension;
using namespace executorch::runtime::etensor;


// CCM RAM size is 64KB on STM32F407. We split it between method metadata and planned tensors.
// Adjust sizes as needed for larger models or more intermediate tensors.

/*
 * Method allocator pool — holds method metadata, operator state, etc.
 * Placed in .ccmram (zero-initialized).
 */

__attribute__((section(".ccmram")))
 static uint8_t method_pool[24 * 1024];
//static uint8_t method_pool[24 * 1024];

/*
 * Planned memory pool — holds intermediate tensors during execution.
 * ExecuTorch memory-plans tensor lifetimes at export time; this pool
 * provides the backing storage for those planned allocations.
 */
//static uint8_t planned_pool[64 * 1024];
__attribute__((section(".ccmram")))
static uint8_t planned_pool[38 * 1024];

/*
 * Input data — static so it has a stable address throughout execution.
 * Stack-allocated arrays can be corrupted if the call stack grows deep
 * during method loading/execution.
 */
static float         input_data[4]  = {1.0f, 2.0f, 3.0f, 4.0f};
static TensorImpl::SizesType    sizes[2]     = {1, 4};
static TensorImpl::DimOrderType dim_order[2] = {0, 1};
static TensorImpl::StridesType  strides[2]   = {4, 1};

int main() {
    // Initialize ExecuTorch runtime (sets up PAL, logging infrastructure)
    runtime_init();

    // Load program from flash-resident byte array.
    // BufferDataLoader takes a pointer + size and serves any byte offset
    // into the buffer — used for both the FlatBuffer program data and
    // the constant segment (model weights/constants stored after the
    // FlatBuffer in the .pte file).
    BufferDataLoader loader(tiny_model_pte, tiny_model_pte_len);

    Result<Program> program_result = Program::load(
        &loader,
        Program::Verification::Minimal);
    if (!program_result.ok()) {
        volatile uint32_t err = (uint32_t)program_result.error();
        (void)err;
        while (1); // inspect err in debugger
    }
    Program program = std::move(program_result.get());

    // Set up memory for method loading.
    // MemoryAllocator: bump allocator for method metadata.
    // HierarchicalAllocator: provides memory arenas for planned tensors.
    // MemoryManager: combines both and is passed to load_method.
    MemoryAllocator method_allocator(sizeof(method_pool), method_pool);
    Span<uint8_t> planned_span(planned_pool, sizeof(planned_pool));
    HierarchicalAllocator planned_allocator({&planned_span, 1});
    MemoryManager memory_manager(&method_allocator, &planned_allocator);

    Result<Method> method_result = program.load_method("forward", &memory_manager);
    if (!method_result.ok()) {
        volatile uint32_t err = (uint32_t)method_result.error();
        (void)err;
        while (1); // inspect err in debugger: 0x14 = OperatorMissing
    }
    Method method = std::move(method_result.get());

    // Construct input tensor.
    // TensorImpl takes: scalar type, number of dimensions, sizes array,
    // data pointer, dim_order array, strides array.
    // All arrays must be static (stable address) — see declarations above.
    TensorImpl input_impl(
        ScalarType::Float,
        /*dim=*/2,
        sizes,
        input_data,
        dim_order,
        strides
    );
    Tensor input_tensor(&input_impl);

    Error set_err = method.set_input(EValue(input_tensor), 0);
    if (set_err != Error::Ok) {
        volatile uint32_t err = (uint32_t)set_err;
        (void)err;
        while (1);
    }

    // Run inference
    Error exec_err = method.execute();
    if (exec_err != Error::Ok) {
        volatile uint32_t err = (uint32_t)exec_err;
        (void)err;
        while (1);
    }

    // Read output tensor
    // Expected for input {1,2,3,4}: x*2+1 = {3,5,7,9}
    EValue output = method.get_output(0);
    Tensor out_tensor = output.toTensor();
    const float* out_data = out_tensor.const_data_ptr<float>();
    int64_t num_elements = out_tensor.numel();

    // Store results in volatile arrays so they survive optimization
    // and are inspectable in GDB at the final while(1).
    volatile float results[4] = {0};
    for (int64_t i = 0; i < num_elements && i < 4; i++) {
        results[i] = out_data[i];
    }

    volatile bool correct =
        results[0] == 3.0f &&
        results[1] == 5.0f &&
        results[2] == 7.0f &&
        results[3] == 9.0f;

    // Halt here. In GDB:
    //   (gdb) print correct    -> should be true
    //   (gdb) print results    -> should be {3, 5, 7, 9}
    while (1) {
        (void)correct;
    }
}
